server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # SPA : toutes les routes renvoient vers index.html (React Router)
    location / {
        try_files $uri $uri/ /index.html;
    }

    location /projects/ {
        expires 7d;
        add_header Cache-Control "public";
    }
}
